language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install pycodestyle
script:
  - python -m unittest discover
  - pycodestyle
      --exclude=.git,__pycache__,parsetab.py
      --ignore=E501
      .
