language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install pycodestyle pylint
script:
  - python -m unittest discover
  - pycodestyle
      --exclude=.git,__pycache__,parsetab.py
      --ignore=E501,W504
      .
  # Ideally, we’d also fail on some/all warnings, but a number of them are nontrivial fixes.
  - pylint
      --disable=not-callable
      --errors-only
      --ignore=CVS,__pycache__,parsetab.py
      darom
